% Function that gives the expression of the aerodynamic stiffness matrix of
% the element and the damping aerodynamic matrix 
%%
% DCFA swept wing assignement
%
% Teamwork
% Team members: Venti Edoardo         944421
%               Zemello Matteo        942003
%               Zucchelli Umberto     952952
%
%
%
function el = el_Ka_assembly(b,el,lambda,alpha,dx)

L=el.L;
c = el.sc.Ymax - el.sc.Ymin ;  % chord
e = -el.sc.yo - 1/4*c; % e -> distance between the shear center (elastic axis) and AC

CLa = el.sc.CLa;


if dx == 1
Ka = [[ 0, 0,                                                                           0,                                                                               0,                                                                              0, 0, 0, 0,                                                                             0,                                                                             0,                                                                              0, 0]
[ 0, 0,                                                                           0,                                                                               0,                                                                              0, 0, 0, 0,                                                                             0,                                                                             0,                                                                              0, 0]
[ 0, 0, (CLa*c*sin(2*lambda))/4 - (6*CLa*c*e*cos(lambda)*(cos(lambda)^2 - 1))/(5*L),      (7*CLa*L*c*cos(lambda)^2)/20 - (CLa*c*e*sin(lambda)*(sin(lambda)^2 - 1))/2,      (CLa*L*c*sin(2*lambda))/20 + (CLa*c*e*cos(lambda)*(cos(lambda)^2 - 1))/10, 0, 0, 0,   (6*CLa*c*e*cos(lambda)*(cos(lambda)^2 - 1))/(5*L) - (CLa*c*sin(2*lambda))/4,    (3*CLa*L*c*cos(lambda)^2)/20 - (CLa*c*e*sin(lambda)*(sin(lambda)^2 - 1))/2,      (CLa*c*e*cos(lambda)*(cos(lambda)^2 - 1))/10 - (CLa*L*c*sin(2*lambda))/20, 0]
[ 0, 0,                                -(CLa*c*e*sin(lambda)*(sin(lambda)^2 - 1))/2,                                                     (CLa*L*c*e*cos(lambda)^3)/3,                                -(CLa*L*c*e*sin(lambda)*(sin(lambda)^2 - 1))/12, 0, 0, 0,                                   (CLa*c*e*sin(lambda)*(sin(lambda)^2 - 1))/2,                                                   (CLa*L*c*e*cos(lambda)^3)/6,                                 (CLa*L*c*e*sin(lambda)*(sin(lambda)^2 - 1))/12, 0]
[ 0, 0,   (CLa*c*e*cos(lambda)*(cos(lambda)^2 - 1))/10 - (CLa*L*c*sin(2*lambda))/20, - (CLa*L^2*c*cos(lambda)^2)/20 - (CLa*L*c*e*sin(lambda)*(sin(lambda)^2 - 1))/12,                              -(2*CLa*L*c*e*cos(lambda)*(cos(lambda)^2 - 1))/15, 0, 0, 0,     (CLa*L*c*sin(2*lambda))/20 - (CLa*c*e*cos(lambda)*(cos(lambda)^2 - 1))/10, (CLa*L*c*e*sin(lambda)*(sin(lambda)^2 - 1))/12 - (CLa*L^2*c*cos(lambda)^2)/30, (CLa*c*sin(2*lambda)*L^2)/120 + (CLa*c*e*cos(lambda)*(cos(lambda)^2 - 1)*L)/30, 0]
[ 0, 0,                                                                           0,                                                                               0,                                                                              0, 0, 0, 0,                                                                             0,                                                                             0,                                                                              0, 0]
[ 0, 0,                                                                           0,                                                                               0,                                                                              0, 0, 0, 0,                                                                             0,                                                                             0,                                                                              0, 0]
[ 0, 0,                                                                           0,                                                                               0,                                                                              0, 0, 0, 0,                                                                             0,                                                                             0,                                                                              0, 0]
[ 0, 0, (CLa*c*sin(2*lambda))/4 + (6*CLa*c*e*cos(lambda)*(cos(lambda)^2 - 1))/(5*L),      (3*CLa*L*c*cos(lambda)^2)/20 + (CLa*c*e*sin(lambda)*(sin(lambda)^2 - 1))/2,    - (CLa*L*c*sin(2*lambda))/20 - (CLa*c*e*cos(lambda)*(cos(lambda)^2 - 1))/10, 0, 0, 0, - (CLa*c*sin(2*lambda))/4 - (6*CLa*c*e*cos(lambda)*(cos(lambda)^2 - 1))/(5*L),    (7*CLa*L*c*cos(lambda)^2)/20 + (CLa*c*e*sin(lambda)*(sin(lambda)^2 - 1))/2,      (CLa*L*c*sin(2*lambda))/20 - (CLa*c*e*cos(lambda)*(cos(lambda)^2 - 1))/10, 0]
[ 0, 0,                                -(CLa*c*e*sin(lambda)*(sin(lambda)^2 - 1))/2,                                                     (CLa*L*c*e*cos(lambda)^3)/6,                                 (CLa*L*c*e*sin(lambda)*(sin(lambda)^2 - 1))/12, 0, 0, 0,                                   (CLa*c*e*sin(lambda)*(sin(lambda)^2 - 1))/2,                                                   (CLa*L*c*e*cos(lambda)^3)/3,                                -(CLa*L*c*e*sin(lambda)*(sin(lambda)^2 - 1))/12, 0]
[ 0, 0,   (CLa*L*c*sin(2*lambda))/20 + (CLa*c*e*cos(lambda)*(cos(lambda)^2 - 1))/10,   (CLa*L^2*c*cos(lambda)^2)/30 + (CLa*L*c*e*sin(lambda)*(sin(lambda)^2 - 1))/12, (CLa*L*c*e*cos(lambda)*(cos(lambda)^2 - 1))/30 - (CLa*L^2*c*sin(2*lambda))/120, 0, 0, 0,   - (CLa*L*c*sin(2*lambda))/20 - (CLa*c*e*cos(lambda)*(cos(lambda)^2 - 1))/10, (CLa*L^2*c*cos(lambda)^2)/20 - (CLa*L*c*e*sin(lambda)*(sin(lambda)^2 - 1))/12,                              -(2*CLa*L*c*e*cos(lambda)*(cos(lambda)^2 - 1))/15, 0]
[ 0, 0,                                                                           0,                                                                               0,                                                                              0, 0, 0, 0,                                                                             0,                                                                             0,                                                                              0, 0]];

Ca = [[ 0, 0,                                                                                                                                                     0,                                                                                    0,                                                                                                                                                        0, 0, 0, 0,                                                                                                                                                       0,                                                                                  0,                                                                                                                                                  0, 0]
[ 0, 0,                                                                                                                                                     0,                                                                                    0,                                                                                                                                                        0, 0, 0, 0,                                                                                                                                                       0,                                                                                  0,                                                                                                                                                        0, 0]
[ 0, 0,                               (pi*c^2*cos(lambda)*sin(lambda))/2 - (26*pi*L*c*cos(lambda))/35 - (3*c^2*pi*cos(lambda)*sin(lambda)^2*(c - 8*e))/(20*L),      (7*pi*L*c^2*cos(lambda)^2)/20 - (c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/32,    (cos(lambda)*((pi*L*c^3*sin(lambda)^2)/80 - (pi*L*c^2*e*sin(lambda)^2)/10))/L + (11*pi*L^2*c*cos(lambda))/105 + (pi*L*c^2*cos(lambda)*sin(lambda))/10, 0, 0, 0,                                  (3*c^2*pi*cos(lambda)*sin(lambda)^2*(c - 8*e))/(20*L) - (9*pi*L*c*cos(lambda))/35 - (pi*c^2*cos(lambda)*sin(lambda))/2,    (3*pi*L*c^2*cos(lambda)^2)/20 - (c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/32,    (cos(lambda)*((pi*L*c^3*sin(lambda)^2)/80 - (pi*L*c^2*e*sin(lambda)^2)/10))/L - (13*pi*L^2*c*cos(lambda))/210 - (pi*L*c^2*cos(lambda)*sin(lambda))/10, 0]
[ 0, 0,                                                                     - (c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/32 - (7*pi*L*c*e*cos(lambda)^2)/10,                                               -(L*c^2*pi*cos(lambda)^3*(c - 8*e))/24,                                                                       (pi*L^2*c*e*cos(lambda)^2)/10 - (L*c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/192, 0, 0, 0,                                                                         (c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/32 - (3*pi*L*c*e*cos(lambda)^2)/10,                                             -(L*c^2*pi*cos(lambda)^3*(c - 8*e))/48,                                                                       (L*c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/192 - (pi*L^2*c*e*cos(lambda)^2)/15, 0]
[ 0, 0, (cos(lambda)*((pi*L*c^3*sin(lambda)^2)/80 - (pi*L*c^2*e*sin(lambda)^2)/10))/L + (11*pi*L^2*c*cos(lambda))/105 - (pi*L*c^2*cos(lambda)*sin(lambda))/10, - (pi*L^2*c^2*cos(lambda)^2)/20 - (L*c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/192,                                     - (cos(lambda)*((pi*L^2*c^3*sin(lambda)^2)/60 - (2*pi*L^2*c^2*e*sin(lambda)^2)/15))/L - (2*pi*L^3*c*cos(lambda))/105, 0, 0, 0,   (13*pi*L^2*c*cos(lambda))/210 - (cos(lambda)*((pi*L*c^3*sin(lambda)^2)/80 - (pi*L*c^2*e*sin(lambda)^2)/10))/L + (pi*L*c^2*cos(lambda)*sin(lambda))/10, (L*c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/192 - (pi*L^2*c^2*cos(lambda)^2)/30, (cos(lambda)*((pi*L^2*c^3*sin(lambda)^2)/240 - (pi*L^2*c^2*e*sin(lambda)^2)/30))/L + (pi*L^3*c*cos(lambda))/70 + (pi*L^2*c^2*cos(lambda)*sin(lambda))/60, 0]
[ 0, 0,                                                                                                                                                     0,                                                                                    0,                                                                                                                                                        0, 0, 0, 0,                                                                                                                                                       0,                                                                                  0,                                                                                                                                                        0, 0]
[ 0, 0,                                                                                                                                                     0,                                                                                    0,                                                                                                                                                        0, 0, 0, 0,                                                                                                                                                       0,                                                                                  0,                                                                                                                                                        0, 0]
[ 0, 0,                                                                                                                                                     0,                                                                                    0,                                                                                                                                                        0, 0, 0, 0,                                                                                                                                                       0,                                                                                  0,                                                                                                                                                        0, 0]
[ 0, 0,                                (pi*c^2*cos(lambda)*sin(lambda))/2 - (9*pi*L*c*cos(lambda))/35 + (3*c^2*pi*cos(lambda)*sin(lambda)^2*(c - 8*e))/(20*L),      (3*pi*L*c^2*cos(lambda)^2)/20 + (c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/32,    (13*pi*L^2*c*cos(lambda))/210 - (cos(lambda)*((pi*L*c^3*sin(lambda)^2)/80 - (pi*L*c^2*e*sin(lambda)^2)/10))/L - (pi*L*c^2*cos(lambda)*sin(lambda))/10, 0, 0, 0,                               - (pi*c^2*cos(lambda)*sin(lambda))/2 - (26*pi*L*c*cos(lambda))/35 - (3*c^2*pi*cos(lambda)*sin(lambda)^2*(c - 8*e))/(20*L),    (7*pi*L*c^2*cos(lambda)^2)/20 + (c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/32,    (pi*L*c^2*cos(lambda)*sin(lambda))/10 - (11*pi*L^2*c*cos(lambda))/105 - (cos(lambda)*((pi*L*c^3*sin(lambda)^2)/80 - (pi*L*c^2*e*sin(lambda)^2)/10))/L, 0]
[ 0, 0,                                                                     - (c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/32 - (3*pi*L*c*e*cos(lambda)^2)/10,                                               -(L*c^2*pi*cos(lambda)^3*(c - 8*e))/48,                                                                       (pi*L^2*c*e*cos(lambda)^2)/15 + (L*c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/192, 0, 0, 0,                                                                         (c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/32 - (7*pi*L*c*e*cos(lambda)^2)/10,                                             -(L*c^2*pi*cos(lambda)^3*(c - 8*e))/24,                                                                     - (pi*L^2*c*e*cos(lambda)^2)/10 - (L*c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/192, 0]
[ 0, 0, (cos(lambda)*((pi*L*c^3*sin(lambda)^2)/80 - (pi*L*c^2*e*sin(lambda)^2)/10))/L - (13*pi*L^2*c*cos(lambda))/210 + (pi*L*c^2*cos(lambda)*sin(lambda))/10,   (pi*L^2*c^2*cos(lambda)^2)/30 + (L*c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/192, (cos(lambda)*((pi*L^2*c^3*sin(lambda)^2)/240 - (pi*L^2*c^2*e*sin(lambda)^2)/30))/L + (pi*L^3*c*cos(lambda))/70 - (pi*L^2*c^2*cos(lambda)*sin(lambda))/60, 0, 0, 0, - (cos(lambda)*((pi*L*c^3*sin(lambda)^2)/80 - (pi*L*c^2*e*sin(lambda)^2)/10))/L - (11*pi*L^2*c*cos(lambda))/105 - (pi*L*c^2*cos(lambda)*sin(lambda))/10, (pi*L^2*c^2*cos(lambda)^2)/20 - (L*c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/192,                                     - (cos(lambda)*((pi*L^2*c^3*sin(lambda)^2)/60 - (2*pi*L^2*c^2*e*sin(lambda)^2)/15))/L - (2*pi*L^3*c*cos(lambda))/105, 0]
[ 0, 0,                                                                                                                                                     0,                                                                                    0,                                                                                                                                                        0, 0, 0, 0,                                                                                                                                                       0,                                                                                  0,                                                                                                                                                        0, 0]];

elseif dx == -1
Ka = [[ 0, 0,                                                                           0,                                                                               0,                                                                              0, 0, 0, 0,                                                                             0,                                                                             0,                                                                              0, 0]
[ 0, 0,                                                                           0,                                                                               0,                                                                              0, 0, 0, 0,                                                                             0,                                                                             0,                                                                              0, 0]
[ 0, 0, (CLa*c*sin(2*lambda))/4 - (6*CLa*c*e*cos(lambda)*(cos(lambda)^2 - 1))/(5*L),      (CLa*c*e*sin(lambda)*(sin(lambda)^2 - 1))/2 - (7*CLa*L*c*cos(lambda)^2)/20,      (CLa*L*c*sin(2*lambda))/20 + (CLa*c*e*cos(lambda)*(cos(lambda)^2 - 1))/10, 0, 0, 0,   (6*CLa*c*e*cos(lambda)*(cos(lambda)^2 - 1))/(5*L) - (CLa*c*sin(2*lambda))/4,    (CLa*c*e*sin(lambda)*(sin(lambda)^2 - 1))/2 - (3*CLa*L*c*cos(lambda)^2)/20,      (CLa*c*e*cos(lambda)*(cos(lambda)^2 - 1))/10 - (CLa*L*c*sin(2*lambda))/20, 0]
[ 0, 0,                                 (CLa*c*e*sin(lambda)*(sin(lambda)^2 - 1))/2,                                                     (CLa*L*c*e*cos(lambda)^3)/3,                                 (CLa*L*c*e*sin(lambda)*(sin(lambda)^2 - 1))/12, 0, 0, 0,                                  -(CLa*c*e*sin(lambda)*(sin(lambda)^2 - 1))/2,                                                   (CLa*L*c*e*cos(lambda)^3)/6,                                -(CLa*L*c*e*sin(lambda)*(sin(lambda)^2 - 1))/12, 0]
[ 0, 0,   (CLa*c*e*cos(lambda)*(cos(lambda)^2 - 1))/10 - (CLa*L*c*sin(2*lambda))/20,   (CLa*L^2*c*cos(lambda)^2)/20 + (CLa*L*c*e*sin(lambda)*(sin(lambda)^2 - 1))/12,                              -(2*CLa*L*c*e*cos(lambda)*(cos(lambda)^2 - 1))/15, 0, 0, 0,     (CLa*L*c*sin(2*lambda))/20 - (CLa*c*e*cos(lambda)*(cos(lambda)^2 - 1))/10, (CLa*L^2*c*cos(lambda)^2)/30 - (CLa*L*c*e*sin(lambda)*(sin(lambda)^2 - 1))/12, (CLa*c*sin(2*lambda)*L^2)/120 + (CLa*c*e*cos(lambda)*(cos(lambda)^2 - 1)*L)/30, 0]
[ 0, 0,                                                                           0,                                                                               0,                                                                              0, 0, 0, 0,                                                                             0,                                                                             0,                                                                              0, 0]
[ 0, 0,                                                                           0,                                                                               0,                                                                              0, 0, 0, 0,                                                                             0,                                                                             0,                                                                              0, 0]
[ 0, 0,                                                                           0,                                                                               0,                                                                              0, 0, 0, 0,                                                                             0,                                                                             0,                                                                              0, 0]
[ 0, 0, (CLa*c*sin(2*lambda))/4 + (6*CLa*c*e*cos(lambda)*(cos(lambda)^2 - 1))/(5*L),    - (3*CLa*L*c*cos(lambda)^2)/20 - (CLa*c*e*sin(lambda)*(sin(lambda)^2 - 1))/2,    - (CLa*L*c*sin(2*lambda))/20 - (CLa*c*e*cos(lambda)*(cos(lambda)^2 - 1))/10, 0, 0, 0, - (CLa*c*sin(2*lambda))/4 - (6*CLa*c*e*cos(lambda)*(cos(lambda)^2 - 1))/(5*L),  - (7*CLa*L*c*cos(lambda)^2)/20 - (CLa*c*e*sin(lambda)*(sin(lambda)^2 - 1))/2,      (CLa*L*c*sin(2*lambda))/20 - (CLa*c*e*cos(lambda)*(cos(lambda)^2 - 1))/10, 0]
[ 0, 0,                                 (CLa*c*e*sin(lambda)*(sin(lambda)^2 - 1))/2,                                                     (CLa*L*c*e*cos(lambda)^3)/6,                                -(CLa*L*c*e*sin(lambda)*(sin(lambda)^2 - 1))/12, 0, 0, 0,                                  -(CLa*c*e*sin(lambda)*(sin(lambda)^2 - 1))/2,                                                   (CLa*L*c*e*cos(lambda)^3)/3,                                 (CLa*L*c*e*sin(lambda)*(sin(lambda)^2 - 1))/12, 0]
[ 0, 0,   (CLa*L*c*sin(2*lambda))/20 + (CLa*c*e*cos(lambda)*(cos(lambda)^2 - 1))/10, - (CLa*L^2*c*cos(lambda)^2)/30 - (CLa*L*c*e*sin(lambda)*(sin(lambda)^2 - 1))/12, (CLa*L*c*e*cos(lambda)*(cos(lambda)^2 - 1))/30 - (CLa*L^2*c*sin(2*lambda))/120, 0, 0, 0,   - (CLa*L*c*sin(2*lambda))/20 - (CLa*c*e*cos(lambda)*(cos(lambda)^2 - 1))/10, (CLa*L*c*e*sin(lambda)*(sin(lambda)^2 - 1))/12 - (CLa*L^2*c*cos(lambda)^2)/20,                              -(2*CLa*L*c*e*cos(lambda)*(cos(lambda)^2 - 1))/15, 0]
[ 0, 0,                                                                           0,                                                                               0,                                                                              0, 0, 0, 0,                                                                             0,                                                                             0,                                                                              0, 0]];

Ca = [[ 0, 0,                                                                                                                                                     0,                                                                                    0,                                                                                                                                                        0, 0, 0, 0,                                                                                                                                                       0,                                                                                  0,                                                                                                                                                  0, 0]
[ 0, 0,                                                                                                                                                     0,                                                                                    0,                                                                                                                                                        0, 0, 0, 0,                                                                                                                                                       0,                                                                                  0,                                                                                                                                                        0, 0]
[ 0, 0,                               (pi*c^2*cos(lambda)*sin(lambda))/2 - (26*pi*L*c*cos(lambda))/35 - (3*c^2*pi*cos(lambda)*sin(lambda)^2*(c - 8*e))/(20*L),      (c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/32 - (7*pi*L*c^2*cos(lambda)^2)/20,    (cos(lambda)*((pi*L*c^3*sin(lambda)^2)/80 - (pi*L*c^2*e*sin(lambda)^2)/10))/L + (11*pi*L^2*c*cos(lambda))/105 + (pi*L*c^2*cos(lambda)*sin(lambda))/10, 0, 0, 0,                                  (3*c^2*pi*cos(lambda)*sin(lambda)^2*(c - 8*e))/(20*L) - (9*pi*L*c*cos(lambda))/35 - (pi*c^2*cos(lambda)*sin(lambda))/2,    (c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/32 - (3*pi*L*c^2*cos(lambda)^2)/20,    (cos(lambda)*((pi*L*c^3*sin(lambda)^2)/80 - (pi*L*c^2*e*sin(lambda)^2)/10))/L - (13*pi*L^2*c*cos(lambda))/210 - (pi*L*c^2*cos(lambda)*sin(lambda))/10, 0]
[ 0, 0,                                                                       (c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/32 + (7*pi*L*c*e*cos(lambda)^2)/10,                                               -(L*c^2*pi*cos(lambda)^3*(c - 8*e))/24,                                                                       (L*c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/192 - (pi*L^2*c*e*cos(lambda)^2)/10, 0, 0, 0,                                                                         (3*pi*L*c*e*cos(lambda)^2)/10 - (c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/32,                                             -(L*c^2*pi*cos(lambda)^3*(c - 8*e))/48,                                                                       (pi*L^2*c*e*cos(lambda)^2)/15 - (L*c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/192, 0]
[ 0, 0, (cos(lambda)*((pi*L*c^3*sin(lambda)^2)/80 - (pi*L*c^2*e*sin(lambda)^2)/10))/L + (11*pi*L^2*c*cos(lambda))/105 - (pi*L*c^2*cos(lambda)*sin(lambda))/10,   (pi*L^2*c^2*cos(lambda)^2)/20 + (L*c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/192,                                     - (cos(lambda)*((pi*L^2*c^3*sin(lambda)^2)/60 - (2*pi*L^2*c^2*e*sin(lambda)^2)/15))/L - (2*pi*L^3*c*cos(lambda))/105, 0, 0, 0,   (13*pi*L^2*c*cos(lambda))/210 - (cos(lambda)*((pi*L*c^3*sin(lambda)^2)/80 - (pi*L*c^2*e*sin(lambda)^2)/10))/L + (pi*L*c^2*cos(lambda)*sin(lambda))/10, (pi*L^2*c^2*cos(lambda)^2)/30 - (L*c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/192, (cos(lambda)*((pi*L^2*c^3*sin(lambda)^2)/240 - (pi*L^2*c^2*e*sin(lambda)^2)/30))/L + (pi*L^3*c*cos(lambda))/70 + (pi*L^2*c^2*cos(lambda)*sin(lambda))/60, 0]
[ 0, 0,                                                                                                                                                     0,                                                                                    0,                                                                                                                                                        0, 0, 0, 0,                                                                                                                                                       0,                                                                                  0,                                                                                                                                                        0, 0]
[ 0, 0,                                                                                                                                                     0,                                                                                    0,                                                                                                                                                        0, 0, 0, 0,                                                                                                                                                       0,                                                                                  0,                                                                                                                                                        0, 0]
[ 0, 0,                                                                                                                                                     0,                                                                                    0,                                                                                                                                                        0, 0, 0, 0,                                                                                                                                                       0,                                                                                  0,                                                                                                                                                        0, 0]
[ 0, 0,                                (pi*c^2*cos(lambda)*sin(lambda))/2 - (9*pi*L*c*cos(lambda))/35 + (3*c^2*pi*cos(lambda)*sin(lambda)^2*(c - 8*e))/(20*L),    - (3*pi*L*c^2*cos(lambda)^2)/20 - (c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/32,    (13*pi*L^2*c*cos(lambda))/210 - (cos(lambda)*((pi*L*c^3*sin(lambda)^2)/80 - (pi*L*c^2*e*sin(lambda)^2)/10))/L - (pi*L*c^2*cos(lambda)*sin(lambda))/10, 0, 0, 0,                               - (pi*c^2*cos(lambda)*sin(lambda))/2 - (26*pi*L*c*cos(lambda))/35 - (3*c^2*pi*cos(lambda)*sin(lambda)^2*(c - 8*e))/(20*L),  - (7*pi*L*c^2*cos(lambda)^2)/20 - (c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/32,    (pi*L*c^2*cos(lambda)*sin(lambda))/10 - (11*pi*L^2*c*cos(lambda))/105 - (cos(lambda)*((pi*L*c^3*sin(lambda)^2)/80 - (pi*L*c^2*e*sin(lambda)^2)/10))/L, 0]
[ 0, 0,                                                                       (c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/32 + (3*pi*L*c*e*cos(lambda)^2)/10,                                               -(L*c^2*pi*cos(lambda)^3*(c - 8*e))/48,                                                                     - (pi*L^2*c*e*cos(lambda)^2)/15 - (L*c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/192, 0, 0, 0,                                                                         (7*pi*L*c*e*cos(lambda)^2)/10 - (c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/32,                                             -(L*c^2*pi*cos(lambda)^3*(c - 8*e))/24,                                                                       (pi*L^2*c*e*cos(lambda)^2)/10 + (L*c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/192, 0]
[ 0, 0, (cos(lambda)*((pi*L*c^3*sin(lambda)^2)/80 - (pi*L*c^2*e*sin(lambda)^2)/10))/L - (13*pi*L^2*c*cos(lambda))/210 + (pi*L*c^2*cos(lambda)*sin(lambda))/10, - (pi*L^2*c^2*cos(lambda)^2)/30 - (L*c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/192, (cos(lambda)*((pi*L^2*c^3*sin(lambda)^2)/240 - (pi*L^2*c^2*e*sin(lambda)^2)/30))/L + (pi*L^3*c*cos(lambda))/70 - (pi*L^2*c^2*cos(lambda)*sin(lambda))/60, 0, 0, 0, - (cos(lambda)*((pi*L*c^3*sin(lambda)^2)/80 - (pi*L*c^2*e*sin(lambda)^2)/10))/L - (11*pi*L^2*c*cos(lambda))/105 - (pi*L*c^2*cos(lambda)*sin(lambda))/10, (L*c^2*pi*sin(2*lambda)*cos(lambda)*(c - 8*e))/192 - (pi*L^2*c^2*cos(lambda)^2)/20,                                     - (cos(lambda)*((pi*L^2*c^3*sin(lambda)^2)/60 - (2*pi*L^2*c^2*e*sin(lambda)^2)/15))/L - (2*pi*L^3*c*cos(lambda))/105, 0]
[ 0, 0,                                                                                                                                                     0,                                                                                    0,                                                                                                                                                        0, 0, 0, 0,                                                                                                                                                       0,                                                                                  0,                                                                                                                                                        0, 0]];


end

el.Ka=sparse(Ka);

el.Ca=sparse(Ca); 
 
end


